### ISSUE TITLE
It sound good but I dont know how it works.

### ISSUE THREAD

**Issue by cheoAlejo** [Gera-IT/redmine_edit_issues_inline#1]
I don't see anything new at the issues page.

**Comment by avdept** [comment]
Docs might be a little outdated. Please make sure you've enabled plugin in project's modules. After this, when you hover over any field on issue list, there should be marker to start inline editing

**Comment by cheoAlejo** [comment]
Hey thanks, it works.

**Comment by avdept** [comment]
Feel free to report any issues, if you find one

**Comment by cheoAlejo** [comment]
Fast editing ! Very usefull.
